// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/planning/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/forecasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/forecasts">> = Specific
  const handler = {} as typeof import("../../src/app/planning/forecasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/intake">> = Specific
  const handler = {} as typeof import("../../src/app/planning/intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/replenishment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/replenishment">> = Specific
  const handler = {} as typeof import("../../src/app/planning/replenishment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/reports">> = Specific
  const handler = {} as typeof import("../../src/app/planning/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/workbench/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/workbench">> = Specific
  const handler = {} as typeof import("../../src/app/planning/workbench/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yard/check-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yard/check-in">> = Specific
  const handler = {} as typeof import("../../src/app/yard/check-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yard/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yard/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/yard/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yard/docks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yard/docks">> = Specific
  const handler = {} as typeof import("../../src/app/yard/docks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yard/exceptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yard/exceptions">> = Specific
  const handler = {} as typeof import("../../src/app/yard/exceptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yard/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yard/map">> = Specific
  const handler = {} as typeof import("../../src/app/yard/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yard/reports">> = Specific
  const handler = {} as typeof import("../../src/app/yard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
